// Generated by IcedCoffeeScript 108.0.11
(function() {
  var crypto_secretbox_NONCEBYTES, prng, uint64be;

  crypto_secretbox_NONCEBYTES = 24;

  prng = require('crypto').prng;

  uint64be = require('uint64be');

  exports.nonceForSenderKeySecretBox = function() {
    return new Buffer('saltpack_sender_key_sbox');
  };

  exports.nonceForPayloadKeyBox = function() {
    return new Buffer('saltpack_payload_key_box');
  };

  exports.nonceForMACKeyBox = function(headerHash) {
    if (headerHash.length !== 64) {
      throw new Error('Header hash shorter than expected');
    }
    return new Buffer(headerHash.slice(0, crypto_secretbox_NONCEBYTES));
  };

  exports.nonceForChunkSecretBox = function(encryptionBlockNumber) {
    var nonce;
    nonce = new Buffer('saltpack_ploadsb');
    return Buffer.concat([nonce, uint64be.encode(encryptionBlockNumber)]);
  };

}).call(this);
